##Fancy Indexing
you can Pick elements from specific positions using a list/array of indices.

In [1]:
import numpy as np

In [3]:
arr = np.array([2,4,5,6,7,8])
print(arr[3]) # Access single index
print(arr[[3,5]]) # Access multiple indices

6
[6 8]


You can do this fancy indexing in 2D Matrix aswell

In [6]:
matrix = np.arange(1,19).reshape(3,6)
print(matrix,"\n")

print(matrix[[0,2],[1,4]]) #[[row],[columns]]
                           # 2 = (0,1),
                           # 17 = (2,4)


[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]] 

[ 2 17]


##Conditional Selection
Find values based on conditions or replace them.

In [15]:
arr = np.array([2,4,5,6,7,8])
print(arr>6, '\n')
print(arr[arr>6])

[False False False False  True  True] 

[7 8]


In [14]:
print(np.where(arr<6)) # Give indices of elements < 6
print(np.where(arr<6,arr,0)) # Give values < 6 and make rest of the values = 0
print(np.where(arr<6,arr,10)) # Give values < 6 and make rest of the values = 10

(array([0, 1, 2]),)
[2 4 5 0 0 0]
[ 2  4  5 10 10 10]


##Sorting & Ordering
np.sort() → returns sorted array

np.argsort() → returns indices of sorted order

In [18]:
arr = np.array([23,45,21,65,10,18,45])
print(np.sort(arr))
print(np.argsort(arr)) # Returns indices of sorted ordder

[10 18 21 23 45 45 65]
[4 5 2 0 6 1 3]


##Concatenation & Stacking

In [21]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.concatenate([a,b]))
print(np.concat([a,b]), '\n')
print(np.stack([a,b]))

[1 2 3 4 5 6]
[1 2 3 4 5 6] 

[[1 2 3]
 [4 5 6]]


Vertical & Horizontal Stacking

In [26]:
# matrix
a = np.array([[1,2,3],[6,7,8]])
b = np.array([[4,5,6],[15,16,17]])
print(a,'\n')
print(b)




[[1 2 3]
 [6 7 8]] 

[[ 4  5  6]
 [15 16 17]]


In [27]:
print(np.vstack([a,b]),"\n")

[[ 1  2  3]
 [ 6  7  8]
 [ 4  5  6]
 [15 16 17]] 



In [28]:
print(np.vstack([b,a]))

[[ 4  5  6]
 [15 16 17]
 [ 1  2  3]
 [ 6  7  8]]


In [29]:
print(np.hstack([a,b]),'\n')

[[ 1  2  3  4  5  6]
 [ 6  7  8 15 16 17]] 



In [31]:
print(np.hstack([b,a]),'\n')

[[ 4  5  6  1  2  3]
 [15 16 17  6  7  8]] 



In [32]:
np.concat([a,b]) # It is = vstack([a,b])

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [ 4,  5,  6],
       [15, 16, 17]])