# **Using NumPy**

Once you've installed NumPy you can import it as a library:

In [3]:
import numpy as np

ModuleNotFoundError: No module named 'numpy'

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [ ]:
a = [1,2,3,4,5]
arr = np.array(a)
arr

array([1, 2, 3, 4, 5])

In [ ]:
arr = np.array([1,2,3,4,5])
arr.dtype

dtype('int64')

In [ ]:
arr = np.array(["1",3,4,5,]) # NumPy's type promotion rules require all elements to have a common dtype,
                             # so it promotes everything to strings
arr.dtype
print(arr)

['1' '3' '4' '5']


Lets create a matrix using list

In [ ]:
a = [[1,2,3],[4,5,6],[7,8,9]]
print(a)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [ ]:
arr = np.array(a)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr = np.linspace(0,10,5) # Give values at equal distance in an interval
arr

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
np.eye(5,3) #identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.random.rand(5,4) # random values between 0 - 1

array([[0.56521541, 0.13690473, 0.60527215, 0.30768469],
       [0.38276736, 0.92024317, 0.20539376, 0.18956897],
       [0.5255363 , 0.97049479, 0.61145543, 0.45626922],
       [0.40850503, 0.570339  , 0.55994262, 0.38423373],
       [0.36691891, 0.87439045, 0.31306924, 0.73624755]])

In [ ]:
np.random.randint(1,100,(3,4)) #random integers [low,high,size]

array([[67, 45, 66, 35],
       [82, 55, 72, 90],
       [71, 58, 11, 21]])

In [ ]:
np.random.randn(5,6) # matrix of sixe 5,6 with random values between (-3 - +3)

array([[-0.16898961,  1.53209264, -2.33541473,  1.30046948,  0.15119239,
        -0.48416988],
       [-0.52376394, -0.04927607, -0.95899159, -0.61291832,  0.3440442 ,
        -2.66611902],
       [-0.95187258,  0.6975635 , -0.85546828,  0.25262644, -1.52470982,
         1.67117327],
       [ 0.65402827, -1.83759709, -0.06775666, -1.92578503,  2.60291927,
         0.47845391],
       [ 0.26574541,  0.62115257,  0.27862094, -1.76254312, -0.02826038,
        -0.05224369]])

Now lets see how matlix looks like using numpy arrays

## Built-in Methods

there are lots of build in methods to create an array lets create some and see

np.zeros(), np.ones(), np.full()

np.arange(), np.linspace()

np.eye()

In [ ]:
np.zeros([4,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr = np.ones([3,4])
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.full([3,4],45)

array([[45, 45, 45, 45],
       [45, 45, 45, 45],
       [45, 45, 45, 45]])

In [4]:
arr1 = np.arange(5)
arr2 = np.arange(5,10)
arr3 = np.arange(5,10,2)
arr1

NameError: name 'np' is not defined

arange → step-based values

linspace → fixed number of values

eye → identity matrix

rand → random floats (0–1)

randint → random integers in a range

randn → random values from bell curve distribution

In [ ]:
arr = np.array([10,20,30]) # Scalar addition
arr + 5

array([15, 25, 35])

In [ ]:
a1 = np.array([1, 2, 3]) # Element-wise multiplicationn
a2 = np.array([4, 5, 6])
a1 * a2

array([ 4, 10, 18])