##1. Attributes of an Array

Introduce attributes that describe the array.

Attributes: .shape, .ndim, .size, .dtype.

In [3]:
import numpy as np

In [5]:
arr = np.array([[2,4,3,1],[3,5,2,5]])
print(arr)
print(arr.shape) # Rows and colums of the array
print(arr.ndim) # Dimension (3d arrays are called tensors which are basis of tensor flow library)
print(arr.size) # total  number of elements
print(arr.dtype) # data type of elements

[[2 4 3 1]
 [3 5 2 5]]
(2, 4)
2
8
int64


##Indexing and Slicing
Now we have Indexing and slicing aswell and for that we are going to see 1d and 2d indexing lets start with **1D indexing** and it is similar to list.

In [6]:
arr = np.array([2,4,3,1])
print(arr[0])  # positive indexing starting from 0
print(arr[-3]) # negative indexing starting from 1

2
4


Now lets see the 2D indexing aswell

In [12]:
arr = np.array([[2,4,3,1],[3,5,2,5],[1,2,3,4]])
print(arr,'\n')
print(arr[0]) # 1st value target rows
print(arr[2,0])
print(arr[0,2]) # target both rows and colums

[[2 4 3 1]
 [3 5 2 5]
 [1 2 3 4]] 

[2 4 3 1]
1
3


Now we can also do the slicing lets see the **slicing in 1D**

In [14]:
# slicing in 1d is similar to string slicing [start(0),stop(exclusive),step(1)]
arr = np.array([2,4,3,1])
print(arr[0:3])

[2 4 3]


1D slicing was really easy now lets see the **slicing in 2D**

In [16]:
arr = np.array([[2,4,3,1],[3,5,2,5],[1,2,3,4]])
print(arr,'\n')
print(arr[0:2,1:3]) # [rows,colums]

[[2 4 3 1]
 [3 5 2 5]
 [1 2 3 4]] 

[[4 3]
 [5 2]]


There is one more thing known as **Boolean indexing**

In [17]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr%2==0) # Give true or False
print(arr[arr%2==0]) #Print true values
print(arr>6)
print(arr[arr>6])

[False  True False  True False  True False  True False]
[2 4 6 8]
[False False False False False False  True  True  True]
[7 8 9]


In [19]:
arr = np.array([[2,4,3,1],[3,5,2,5],[1,2,3,4]])
print(arr,'\n')
print(arr[arr>3]) # 1-d array

[[2 4 3 1]
 [3 5 2 5]
 [1 2 3 4]] 

[4 5 5 4]


## Reshaping the Array

you can also reshape the Array as you like but be accurate about the dimensions

In [21]:
arr = np.arange(1,31).reshape(6,5)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


## Flattening of an array

you can convert the 2D array to 1D using the Flattening Function

In [24]:
arr.flatten() # Convert 2-D array into 1-D

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

Element-wise division

In [27]:
a = np.array([10,20,30])
b = np.array([2,4,5])
a/b

array([5., 5., 6.])