##Numpy array operations

Lets first see how arrays behave like “vectors/matrices” when operations happen element-wise.

In [1]:
import numpy as np

In [5]:
a = [1,2,3,4]
b = [10,20,30,40]
print(a+b,'\n') # String concatination
arr1 = np.array(a)
arr2 = np.array(b)
print(arr1+arr2)
print(arr1*arr2)
print(arr1-arr2)
print(arr2/arr1)
print(arr2//arr1)

[1, 2, 3, 4, 10, 20, 30, 40] 

[11 22 33 44]
[ 10  40  90 160]
[ -9 -18 -27 -36]
[10. 10. 10. 10.]
[10 10 10 10]


These things are already different from List and if we talk about one more special power it is **Broadcasting**

Even these things work with different shaped array the calculations will happen on every row. but dimensions must match

In [9]:
a = [1,2,3,4] # list
print(a * 2)

arr1 = np.array(a) # array
print(arr1 * 2)

arr2 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr2 * 5)

[1, 2, 3, 4, 1, 2, 3, 4]
[2 4 6 8]
[[ 5 10 15 20]
 [25 30 35 40]]


#Aggregate Functions

These functions are used to calculate the statistics on arrays.

In [10]:
arr = np.array([1,2,3,4,5])
print(arr.sum())
print(arr.min())
print(arr.max())
print(arr.mean())
print(arr.std()) # standard deviation
print(arr.var()) # variance

15
1
5
3.0
1.4142135623730951
2.0


You can also do the axis based operations row-Wise and Colum-wise

In [13]:
arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [7,8,5,7]])
print(arr.sum(axis=0)) # column-wise sum
print(arr.sum(axis=1)) # row-wise sum

[13 16 15 19]
[10 26 27]


In [14]:
print(np.sum(arr,axis=0)) # different method for writing
print(np.sum(arr,axis=1))

[13 16 15 19]
[10 26 27]


In [16]:
print(np.array([1,2,3])**2)

[1 4 9]


In [17]:
print(np.array([10,20,30])//4)

[2 5 7]
